### ISSUE TITLE
[feature] Add possibility to skip invalide certificate check

### ISSUE THREAD

**Issue by skyheis** [davidmytton/url-verifier#9]
Hi,
I'm using your project, it has been very useful to me, but I needed to make insecure request (as 'curl -k ...').
I made a couple edit to your library and I would like to make it usable for everyone.
How can I do it?

Thanks,
Giulio

**Comment by davidmytton** [comment]
Hi @skyheis - thanks! I'll happily consider any pull request if you want to submit the changes you've made.

**Comment by skyheis** [comment]
I made the pull request, thanks @davidmytton!

**Comment by davidmytton** [comment]
Closed by https://github.com/davidmytton/url-verifier/pull/10
